#! /bin/sh

wmname LG3D &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
# bspc config border_radius         12
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Reload .Xresources
xrdb -load ~/.Xresources
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# polybar
$HOME/.config/polybar/launch.sh
# Make betterlockscreen generate and cache a background image for :locking
# betterlockscreen -u $HOME/bluehill.jpg
# # Set wallpaper
feh --bg-fill $HOME/dotfiles/city.png
# # Picom
# picom --xrender-sync-fence
# network manager applet
# nm-applet
# ------- Mouse/Touchpad fixes ------
libinput-gestures-setup start
# # ------- Autostart apps ------
# Dunst
dunst &
# typing in Vietnamese
fcitx-autostart &
xautolock -time 50 -locker 'betterlockscreen -l' &
# transer lock should be at last
xss-lock --transfer-sleep-lock -- betterlockscreen -l
